spring:

  datasource:
    url: jdbc:mysql://localhost:3306/ryujin_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: asd1234
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  mustache:
    prefix: classpath:/templates/
    suffix: .mustache